use_frameworks!
platform :ios, '9.0'

target 'WeLoop_Example' do
  pod 'WeLoop', :path => '../'

  target 'WeLoop_Tests' do
    inherit! :search_paths
  end
end

target 'WeLoopSwiftUI' do
  pod 'WeLoop', :path => '../'
end
